### ISSUE TITLE
Implicit ErrorStore for JdbcTableListener doesn't work

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#7500] opened 2024-09-16 12:10 UTC
### Current Behavior

With the following listener errors do not end up in the (implicit) error store:

```
<listener
name="***_RECORDSTORE_listener" 
tableName="***_RECORDSTORE" 
statusField="STATUS" 
timestampField="PROCESSDATETIME" 
statusValueAvailable="ToBeProcessed" 
statusValueInProcess="InProcess" 
statusValueProcessed="Processed" 
statusValueError="Error" 
statusValueHold="Hold" 
keyField="ID" 
messageField="XMLCLOB" 
orderField="ID" 
selectCondition="PROCESSDATETIME IS NULL AND TARGET = '***'" 
className="nl.nn.adapterframework.jdbc.JdbcTableListener"/>
```

We tried adding transactionAttribute="Required" as this is also used at https://github.com/frankframework/frankframework/blob/8db508e2bc2be5dac64bd5bb258f340e33748c0f/test/src/main/configurations/MainConfig/ConfigurationReceivers.xml#L37 but then we got the warning "Receiver [...] sets transactionAttribute=REQUIRED, but has no errorSender or errorStorage. Messages processed with errors will be lost". Adding an errorStorage doesn't help, errors will still not end up in the error store.

### Expected Behavior

A working implicit error store. It would also be nice to have the Frank!Doc explain how it works and whether transactionAttribute is required or should not be added

### Environment Information

FF! 7.9-20231006.001807: ibis4xxx xxx
Running on xxx using IBM WebSphere Application Server/9.0.5.20
Java Version: Java(TM) SE Runtime Environment (8.0.8.25 - pxa6480sr8fp25-20240328_01(SR8 FP25))
Heap size: 768M, total JVM memory: 1044M

**Comment by tnleeuw** [comment] 2024-09-25 12:14
At first glance, the `configure()` code in the Receiver seems to do everything the right way and take into account that the listener has a process-state `ERROR` before giving that warning.

However, the configure code in the Receiver depends on the JdbcListener having been configured first -- the JDBC listener sets its "known process states" during configure.

To my knowledge, we have no way of enforcing this order so the code in the JdbcListener and subclasses will need to be rewritten so that it sets all process states when setting the queries or status values.

**Comment by nielsm5** [comment] 2024-10-14 15:34
We have ReceiverTest in our larva test-set and they all have an ErrorStorage. Could you elaborate what isn't working? Can you see the ErrorStorage in the console? In our test scenarios we test both transational and non-transactional flows, if the exit with state=ERROR is called the message ends up in the ErrorStorage as you would expect.

**Comment by nielsm5** [comment] 2024-10-15 14:33
After looking at the configuration in question the error can easily be pinpointed to the following code block:
![image](https://github.com/user-attachments/assets/d9a0132f-b3ee-4964-93f7-d0d9cfbf39d3)

This basically removes all errors and claims there are non.
Since there is no error, messages won't go to the error storage.

**Comment by nielsm5** [comment] 2024-11-04 15:32
The PROCESSDATETIME  is required to update the status, the selectCondition has the following `selectCondition="PROCESSDATETIME IS NULL AND ...." ` which prevents the status from being updated.

**Comment by nielsm5** [comment] 2024-11-04 17:23
We need to improve the error message stating what's wrong. Columns that are part of the select query and thus select condition may not be null.

**Comment by jjansenvr** [comment] 2024-11-11 10:27
Jaco succeeded in reproducing this issue, why where we not able to do this ourselves?

**Comment by nielsm5** [comment] 2024-11-11 10:56
We have, and merged a fix!?

**Closed by nielsm5** 2024-11-11 10:56 UTC
Labels: Bug
