### ISSUE TITLE
Ladybug is not available on frank2example

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7625] opened 2024-10-07 08:10 UTC
### Current Behavior

See 
![image](https://github.com/user-attachments/assets/ccc24aed-c6c0-479c-8f04-415c5d045e17)

### Expected Behavior

Ladybug should show up in https://frank2example.frankframework.org/.

### Environment Information

FF! 8.3.0-20241003.042327: frank2example
Running on frank2example-frankframework-5c78fdc787-nwprc using Apache Tomcat/10.1.28
Java Version: OpenJDK Runtime Environment (21.0.4+7-LTS)
Heap size: 282.8 MiB, total JVM memory: 448.0 MiB
Free memory: 165.2 MiB, max memory: 100.7 GiB
Free disk space: 33.5 GiB, total disk space: 123.4 GiB
Up since: 2024-10-05 05:23:17 (2d)

**Comment by nielsm5** [comment] 2024-10-07 09:03
Duplicate of #7563

**Closed by nielsm5** 2024-10-07 09:03 UTC
Labels: Bug, Needs Triage
