### ISSUE TITLE
Warn console users when disk space is running low

### ISSUE THREAD

**Issue by Laurens-makel** [frankframework/frankframework#6649] opened 2024-04-11 17:55 UTC
**Describe the issue**
We recently ran into a situation where a deadlock created several GB's of logging to system out on WAS, which resulted in 20kb left on the filesystem...  The cause of this is not a problem in the framework but rather in the adapter implementation.

It would be great when the filesystem space is running low (5-10% of total available), a red coloured message is displayed in the console. which informs users that they need to act before problems occur.

**Comment by nielsm5** [comment] 2024-04-15 11:53
Duplicate of #990

**Closed** 2024-04-15 14:37 UTC
Labels: Frank Console
