### ISSUE TITLE
Time in statistics graph two hours behind

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6582] opened 2024-04-03 16:05 UTC
**Describe the issue**

I just executed HelloWorlds a couple of times and see:

![image](https://github.com/frankframework/frankframework/assets/2970084/3fcc94a9-188a-42cb-a8bc-f5507d05f713)

**Environment**
FF! 8.1.0-20240330.042427: Frank2Example
Running on frank2example-77f5f7fd4b-bjfxq using Apache Tomcat/9.0.87
Java Version: OpenJDK Runtime Environment (17.0.10+7)
Heap size: 166M, total JVM memory: 270M
Free disk space: 223GB, total disk space: 501GB
Up since: 2024-03-30 05:46:35 (4d)

**Comment by nielsm5** [comment] 2024-04-04 14:20
Closing this as it's a duplicate of #4945

**Closed by nielsm5** 2024-04-04 14:20 UTC
Labels: Frank Console
