### ISSUE TITLE
iaf-test MessageStoreSenderAndListener scenario 1 and 3

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#5634] opened 2023-10-27 07:33 UTC
Wanneer je 2x achter elkaar test-iaf draait gaat het volgende scenario fout.
Ik weet niet of de reciever `checkForDuplicates` gebruikt (in dit geval) zo ja kan je `checkForDuplicatesMethod=correlationid` gebruiken.
Anders mogelijk `maxDeliveries=-1`

Scenario fails with 'too many retries'
```
<row number="0"><field name="MESSAGEKEY">94</field><field name="TYPE">E</field><field name="SLOTID">TestMessageStoreSenderAndListener-Queue</field><field name="HOST">ff-ci-larva-15043-81s94-vsdzb-tbwxn</field><field name="MESSAGEID">1</field><field name="CORRELATIONID">Test Tool correlation id(682)</field><field name="MESSAGEDATE">2023-10-26 22:42:48</field><field name="COMMENTS">too many retries; too many retries; exitState [SUCCESS], result [String Message[e571c8fa]: original message [&lt;?xml version='1.0' encoding='UTF-8'?&gt;
&lt;Envelope&gt;
	&lt;Header&gt;
		&lt;MessageID&gt;1&lt;/MessageID&gt;
		&lt;Message contentType="application/xml" encoding="UTF-8"&gt;test, with comma&lt;/Message&gt;
	&lt;/Header&gt;
&lt;/Envelope&gt;
] key1 [a,b,c] key2 [double quote: ["] single quote [']]], exitcode [200]</field><field name="MESSAGE">"&lt;?xml version='1.0' encoding='UTF-8'?&gt;
&lt;Envelope&gt;
	&lt;Header&gt;
		&lt;MessageID&gt;1&lt;/MessageID&gt;
		&lt;Message contentType=""application/xml"" encoding=""UTF-8""&gt;test, with comma&lt;/Message&gt;
	&lt;/Header&gt;
&lt;/Envelope&gt;
","a,b,c","double quote: [""] single quote [']"</field><field name="EXPIRYDATE" null="true"/><field name="LABEL" null="true"/></row>
```

**Reporter**
Sergi

**Comment by jkosternl** [comment] 2023-11-28 11:01
I've tried to reproduce this issue, with the following environments and all environments worked perfectly fine. So, can't reproduce.

1. Docker local Master build, Java 11, only with Tomcat.
2. Docker local Master build, Java 11, Tomcat and MariaDB
3. Docker 7.9 image (`private.docker.nexus.frankframework.org/ff-test:7.9-RC2-SNAPSHOT-tomcat`), Java 8, Tomcat and MariaDB.

After a call with Sergi, we decided to close this issue. He can reopen it, as soon as it reproduces, logging all the details and logs inside this issue.

**Closed by jkosternl** 2023-11-28 11:01 UTC
Labels: Bug
