### ISSUE TITLE
Upgrade aspose

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#3293] opened 2022-06-02 06:44 UTC
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The customer confirmed the newest aspose libraries are acquired so we can upgrade the aspose implemantation within the Framework

**Reporter**
jjansenvr

**Comment by nielsm5** [comment] 2023-12-15 11:13
Duplicate of the already merged #4580.

**Closed by nielsm5** 2023-12-15 11:13 UTC
Labels: Feature, Aspose
