### ISSUE TITLE
Monitoring: When you select a destination, it does not appear in the generated XML

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#8024] opened 2024-11-29 13:33 UTC
### Current Behavior

See 
![image](https://github.com/user-attachments/assets/5712c38a-2ccf-420d-816c-122e5d535140)

I created a monitor with a destination and generated the corresponding XML. I also wrote the XML I expected to see. You see that the destination is not in the generated XML.

### Expected Behavior

The selected destination should appear in the generated XML

### Environment Information

**FF! 9.0.0-20241129.042326**: v500 
Running on **LAPTOP-R1SK28C** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (21.0.2+13-LTS)**
Heap size: **146.0 MiB**, total JVM memory: **264.0 MiB**
Free memory: **118.0 MiB**, max memory: **1.0 GiB**
Free disk space: **117.5 GiB**, total disk space: **464.3 GiB**

**Comment by tnleeuw** [comment] 2024-11-30 14:06
I believe that the XML generation works but @thomaspj10 just fixed a bug with selecting destinations in the front-end. I think this might be the cause of the issue here?

**Comment by nielsm5** [comment] 2024-11-30 15:50
Closing as it's a duplicate of #7969

**Closed by nielsm5** 2024-11-30 15:50 UTC
Labels: Bug, Monitoring, Needs Triage
