### ISSUE TITLE
Skipped pipes show as if they were executed anyways in Ladybug

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#6654] opened 2024-04-12 09:44 UTC
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
If a pipe is skipped because of an IfParam or IfSessionKey condition, it still shows as if it was executed anyways. The output of the pipe and the storeResultInSessionKey sessionkey are both showing the input of the pipe. The only indication that a pipe was skipped is that the output and storeResultInSessionKey sessionkey looks off.

Greying out skipped pipes or any other indication that a pipe was skipped would be very handy.

**Reporter**
M. Lenterman

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment] 2024-04-15 12:03
Duplicate of #6559.

**Closed by nielsm5** 2024-04-15 12:03 UTC
