### ISSUE TITLE
'Timeout stopping receiver' causing 'Adapter [...] in state [STOPPED], cannot process message'

### ISSUE THREAD

**Issue by gvanbrakel** [frankframework/frankframework#4276] opened 2023-01-03 18:20 UTC
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
see mail Richard vd Stel, d.d. 28-12-2022:
```
2022-12-27 04:01:15,457 WARN [GuardTask[stopping receiver [ArchiveDocument_4]]] null task.TimeoutGuard - Thread [Timer-12] executing task [stopping receiver [ArchiveDocument_4]] exceeds timeout of [60] s, interuppting
2022-12-27 04:01:15,458 WARN [Timer-12] null receivers.Receiver - Receiver [ArchiveDocument_4] timeout stopping
2022-12-27 04:01:15,458 WARN [Timer-12] null unmanaged.PollGuard - JMS poll timeout [3] handling restarting receiver [ArchiveDocument_4]
2022-12-27 04:01:15,465 WARN [Timer-12] null unmanaged.PollGuard - JMS poll timeout [3] handling restarted receiver [ArchiveDocument_4]
2022-12-27 04:01:23,090 WARN [GuardTask[stopping receiver [ArchiveDocument_4]]] null task.TimeoutGuard - Thread [ArchiveDocument_4[2]] executing task [stopping receiver [ArchiveDocument_4]] exceeds timeout of [60] s, interuppting
2022-12-27 04:01:23,090 WARN [ArchiveDocument_4[2]] null receivers.Receiver - Receiver [ArchiveDocument_4] timeout stopping
2022-12-27 04:01:23,091 WARN [GuardTask[stopping receiver [ArchiveDocument_4]]] null task.TimeoutGuard - Thread [ArchiveDocument_4[1]] executing task [stopping receiver [ArchiveDocument_4]] exceeds timeout of [60] s, interuppting
2022-12-27 04:01:23,091 WARN [ArchiveDocument_4[1]] null receivers.Receiver - Receiver [ArchiveDocument_4] timeout stopping
```

**Reporter**
Richard

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by tnleeuw** [comment] 2023-01-19 12:52
After studying the code and exactly what happens in the logs the sequence of events is:

1. `PollGuard` tries to stop receiver, thread `[Timer-12]`
2. `TimeoutGuard`  kicks in because thread `[Timer-12]` takes longer than 60s to do that
3. `PollGuard` restarts the receiver
4. Now `TimeoutGuard` kicks in again twice on timeout stopping receiver from threads `[ArchiveDocument_4[1]]` and `[ArchiveDocument_4[2]]` 

After that of course the adapter is stopped.

Questions that I cannot answer yet:
1. Why the timeouts in closing? Likely a deadlock, but from what?
2. Why did threads `[ArchiveDocument_4[1]]` and `[ArchiveDocument_4[2]]` try closing their receivers?

If this situation is reproducible, I would like at least some extra logging to get a stack trace on the point the tripping of timeout-guard was detected in the threads that invoked `Receiver.closeAllResources()`.

**Comment by tnleeuw** [comment] 2023-01-19 22:15
Another observation is that once a PollGuard triggers, it appears the PollGuard is continuously re-created and instantly triggers again so it instantly stops and restarts the receiver which was just restarted.

**Comment by tnleeuw** [comment] 2023-02-21 10:04
I suspect that there may be deadlocks occurring while stopping / starting adapters while at the same time the pollguard tries to restart the adapters.

To be able to debug if this is still a problem after pollguard-frequency has been fixed, a lot of trace-level logging has been added on places where locks are taken in the code.

To enable this trace logging, the following loggers have to be set on TRACE level:

```
nl.nn.adapterframework.core.Adapter
nl.nn.adapterframework.receivers
nl.nn.adapterframework.task.TimeoutGuard
nl.nn.adapterframework.unmanaged
nl.nn.adapterframework.jms.MessagingSource
nl.nn.adapterframework.jms.MessagingSourceFactory
```

This can be done by adding the following lines to the `<Loggers>` section of the Log4J XML configuration file:
```
		<Logger name="nl.nn.adapterframework.core.Adapter" level="TRACE"/>
		<Logger name="nl.nn.adapterframework.receivers" level="TRACE"/>
		<Logger name="nl.nn.adapterframework.task.TimeoutGuard" level="TRACE"/>
		<Logger name="nl.nn.adapterframework.unmanaged" level="TRACE"/>
		<Logger name="nl.nn.adapterframework.jms.MessagingSource" level="TRACE"/>
		<Logger name="nl.nn.adapterframework.jms.MessagingSourceFactory" level="TRACE"/>
```

**Comment by tnleeuw** [comment] 2023-03-24 16:33
The cause of the issue has been identified:
1. If a receiver is stopped, and has EXCEPTION_STOPPING
2. And at that point the adapter is stopped containing that receiver
3. The adapter will forever try to stop the receiver, and hang

This was triggered in the above NN scenario:
1. The Pollguard was active and stopping receiver which were having problems with the ESB connection, causing EXCEPTION_STOPPING status
2. A daily scheduled job was stopping and restarting configurations (and thus adapters)
3. When the timing of the Pollguard intersected with the job to restart adapters, then an adapter would become stuck
4. Due to an implementation-issue with the Pollguard timers it could happen that the Pollguard was restarting receivers very frequently, thus making the likelihood of this condition happening much larger.

**Closed** 2023-11-21 08:48 UTC
