### ISSUE TITLE
(BLOCKING issue in 7.9.0) soap version in wrapper (of sender) is not taken into account when auto is used

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#6032] opened 2023-12-21 10:06 UTC
We have an inbound call `soapVersion=auto`
in our outgoing call we specify `soapVersion=1.1` but it still uses the 1.2 version of the input message. 

**Reporter**
jjansenvr

**To Reproduce**
see email with report 

**Screenshots**

**Configuration**

**Input**

**Environment**
```
7.9.0
```

**Comment by VBPham** [comment] 2024-01-10 06:49
Hi @jkosternl I tried your suggestion of adding `soapNamespaceSessionKey` to the wrappers but I am still getting this stacktrace when the sender tries to unwrap the response. This is with `7.9-RC1-hotfix10`

````txt
2024-01-10 07:40:42,317 INFO [Thread-145] {cid=Test Tool correlation id(5), adapter=GetAccounts_1} processors.ExceptionHandlingPipeProcessor - exception occured, forwarding to exception-forward [exception], exception:

nl.nn.adapterframework.core.PipeRunException: Pipe [- CallBE_SalesforceLogin_UTL_CreateSession_3: wrap output] Unexpected exception during (un)wrapping : Pipe [- CallBE_SalesforceLogin_UTL_CreateSession_3: wrap output] SOAP Body is empty or message is not a SOAP Message
      at nl.nn.adapterframework.soap.SoapWrapperPipe.doPipe(SoapWrapperPipe.java:252) ~[ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      ... suppressed 65 lines
      at nl.nn.adapterframework.pipes.MessageSendingPipe.postProcessOutput(MessageSendingPipe.java:762) ~[ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.pipes.MessageSendingPipe.doPipe(MessageSendingPipe.java:513) ~[ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.pipes.MessageSendingPipe$$FastClassBySpringCGLIB$$b131b2cb.invoke(<generated>) ~[?:?]
      ... suppressed 8 lines
      at nl.nn.adapterframework.pipes.SenderPipe$$EnhancerBySpringCGLIB$$80b1bb02.doPipe(<generated>) ~[?:?]
      ... suppressed 92 lines
      at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:501) [ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:662) [ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1235) [ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1042) [ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.receivers.JavaListener.processRequest(JavaListener.java:170) [ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.receivers.JavaListener.processRequest(JavaListener.java:136) [ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.dispatcher.DispatcherManagerImpl.processRequest(DispatcherManagerImpl.java:123) [service-dispatcher-1.5.jar:?]
      at nl.nn.adapterframework.senders.IbisJavaSender.sendMessage(IbisJavaSender.java:128) [ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      at nl.nn.adapterframework.testtool.SenderThread.run(SenderThread.java:64) [ibis-adapterframework-larva-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
Caused by: nl.nn.adapterframework.core.PipeRunException: Pipe [- CallBE_SalesforceLogin_UTL_CreateSession_3: wrap output] SOAP Body is empty or message is not a SOAP Message
      at nl.nn.adapterframework.soap.SoapWrapperPipe.doPipe(SoapWrapperPipe.java:232) ~[ibis-adapterframework-core-7.9-RC1-hotfix10.jar:7.9-RC1-hotfix10]
      ... 178 more
2024-01-10 07:40:42,323 DEBUG [Thread-145] {cid=Test Tool correlation id(5), adapter=GetAccounts_1} processors.MonitoringPipeProcessor - Pipeline of adapter [GetAccounts_1] messageId [synthetic-message-id-0a00323a--3fd0e1d6_18cf2147ab7_-7ffc] is about to call pipe [InternalError] current result (Message) [Message[71e09b6b:String]: [<errorMessage timestamp="Wed Jan 10 07:40:42 CET 2024" originator="IAF 7.9-RC1-hotfix10" message="Adapter [GetAccounts_1] msgId [synthetic-message-id-0a00323a--3fd0e1d6_18cf2147ab7_-7ffc]: Pipe [- CallBE_SalesforceLogin_UTL_CreateSession_3: wrap output] Unexpected exception during (un)wrapping : Pipe [- CallBE_SalesforceLogin_UTL_CreateSession_3: wrap output] SOAP Body is empty or message is not a SOAP Message: Pipe [- CallBE_SalesforceLogin_UTL_CreateSession_3: wrap output] SOAP Body is empty or message is not a SOAP Message">
      <location class="nl.nn.adapterframework.core.Adapter" name="GetAccounts_1"/>
      <details>nl.nn.adapterframework.core.PipeRunException: Pipe [- CallBE_SalesforceLogin_UTL_CreateSession_3: wrap output] SOAP Body is empty or message is not a SOAP Message
      at nl.nn.adapterframework.soap.SoapWrapperPipe.doPipe(SoapWrapperPipe.java:232)
      at nl.nn.adapterframework.processors.CorePipeProcessor.processPipe(CorePipeProcessor.java:33)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.CheckMessageSizePipeProcessor.processPipe(CheckMessageSizePipeProcessor.java:38)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.LockerPipeProcessor.processPipe(LockerPipeProcessor.java:62)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.execute(TransactionAttributePipeProcessor.java:96)
      at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.processPipe(TransactionAttributePipeProcessor.java:65)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:59)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:67)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$FastClassBySpringCGLIB$$3159a29c.invoke(&lt;generated&gt;)
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:187)
      at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$EnhancerBySpringCGLIB$$4c35f62f.processPipe(&lt;generated&gt;)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:111)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:198)
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$FastClassBySpringCGLIB$$feb9be85.invoke(&lt;generated&gt;)
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:157)
      at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$fada20c5.processPipe(&lt;generated&gt;)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.ExceptionHandlingPipeProcessor.processPipe(ExceptionHandlingPipeProcessor.java:37)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:77)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.pipes.MessageSendingPipe.postProcessOutput(MessageSendingPipe.java:762)
      at nl.nn.adapterframework.pipes.MessageSendingPipe.doPipe(MessageSendingPipe.java:513)
      at nl.nn.adapterframework.pipes.MessageSendingPipe$$FastClassBySpringCGLIB$$b131b2cb.invoke(&lt;generated&gt;)
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
      at nl.nn.adapterframework.pipes.SenderPipe$$EnhancerBySpringCGLIB$$80b1bb02.doPipe(&lt;generated&gt;)
      at nl.nn.adapterframework.processors.CorePipeProcessor.processPipe(CorePipeProcessor.java:33)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.CheckMessageSizePipeProcessor.processPipe(CheckMessageSizePipeProcessor.java:38)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.LockerPipeProcessor.processPipe(LockerPipeProcessor.java:62)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.execute(TransactionAttributePipeProcessor.java:96)
      at nl.nn.adapterframework.processors.TransactionAttributePipeProcessor.processPipe(TransactionAttributePipeProcessor.java:65)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:59)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor.processPipe(CheckSemaphorePipeProcessor.java:67)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$FastClassBySpringCGLIB$$3159a29c.invoke(&lt;generated&gt;)
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeGetInputFrom(IbisDebuggerAdvice.java:187)
      at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeProcessor$$EnhancerBySpringCGLIB$$4c35f62f.processPipe(&lt;generated&gt;)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:111)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor.processPipe(InputOutputPipeProcessor.java:198)
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$FastClassBySpringCGLIB$$feb9be85.invoke(&lt;generated&gt;)
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:157)
      at sun.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
      at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$fada20c5.processPipe(&lt;generated&gt;)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.ExceptionHandlingPipeProcessor.processPipe(ExceptionHandlingPipeProcessor.java:37)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.MonitoringPipeProcessor.processPipe(MonitoringPipeProcessor.java:77)
      at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
      at nl.nn.adapterframework.processors.CorePipeLineProcessor.processPipeLine(CorePipeLineProcessor.java:236)
      at nl.nn.adapterframework.processors.CorePipeLineProcessor$$FastClassBySpringCGLIB$$cf1091e5.invoke(&lt;generated&gt;)
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102)
      at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:123)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
      at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
      at nl.nn.adapterframework.processors.CorePipeLineProcessor$$EnhancerBySpringCGLIB$$dd8db6e5.processPipeLine(&lt;generated&gt;)
      at nl.nn.adapterframework.processors.LockerPipeLineProcessor.processPipeLine(LockerPipeLineProcessor.java:60)
      at nl.nn.adapterframework.processors.TransactionAttributePipeLineProcessor.processPipeLine(TransactionAttributePipeLineProcessor.java:49)
      at nl.nn.adapterframework.processors.CheckSemaphorePipeLineProcessor.processPipeLine(CheckSemaphorePipeLineProcessor.java:58)
      at nl.nn.adapterframework.processors.CachePipeLineProcessor.processPipeLine(CachePipeLineProcessor.java:41)
      at nl.nn.adapterframework.processors.InputOutputPipeLineProcessor.processPipeLine(InputOutputPipeLineProcessor.java:44)
      at nl.nn.adapterframework.core.PipeLine.process(PipeLine.java:501)
      at nl.nn.adapterframework.core.Adapter.processMessageWithExceptions(Adapter.java:662)
      at nl.nn.adapterframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1235)
      at nl.nn.adapterframework.receivers.Receiver.processRequest(Receiver.java:1042)
      at nl.nn.adapterframework.receivers.JavaListener.processRequest(JavaListener.java:170)
      at nl.nn.adapterframework.receivers.JavaListener.processRequest(JavaListener.java:136)
      at nl.nn.adapterframework.dispatcher.DispatcherManagerImpl.processRequest(DispatcherManagerImpl.java:123)
      at nl.nn.adapterframework.senders.IbisJavaSender.sendMessage(IbisJavaSender.java:128)
      at nl.nn.adapterframework.testtool.SenderThread.run(SenderThread.java:64)
</details>
      <originalMessage messageId="synthetic-message-id-0a00323a--3fd0e1d6_18cf2147ab7_-7ffc" receivedTime="Wed Jan 10 07:40:42 CET 2024">[REDACTED]</originalMessage>
</errorMessage>]]`

**Comment by jkosternl** [comment] 2024-01-10 09:05
> Hi @jkosternl I tried your suggestion of adding `soapNamespaceSessionKey` to the wrappers of pipe `CallBE_SalesforceLogin_UTL_CreateSession_3` but I am still getting this stacktrace when the sender tries to unwrap the response. This is with `7.9-RC1-hotfix10`

Hi @VBPham, thanks for your testing out of our suggested solution. I am quite surprised it had no visible effect. The message in the pipe is still wrong or not properly recognized. 
Can you please create a Ladybug report out of this new situation, so I have more details of the variables/keys/message etc? If it contains sensitive data, please send it to jacobjob@wearefrank.nl

**Comment by jkosternl** [comment] 2024-01-10 17:34
Hi @alisihab and @VBPham, we've got a code fix for this issue. With the fix, you don't need to change your configuration(s). You can roll back the change requested above. 

FYI: We found the real bug. It stored the SoapVersion in the first SoapWrapper (which is NOT in the CallBE_SalesforceLogin_UTL_CreateSession_3 SenderPipe). That version was used to unwrap the message later, which was actually Soap 1.1 from the SalesforceLogin. Now, we've changed the logic so it tries unwrapping first with the stored Soap version, but when that fails, it tries Soap 1.1 too. In that way, no more regression issues will be caused.

**Closed** 2024-01-11 13:35 UTC
Labels: Bug

**Comment by jkosternl** [comment] 2024-01-11 14:46
@VBPham, the fixes are merged into master (8.1), 8.0-branch, 7.9-branch. From tomorrow (Friday 12 Jan), please download the latest `7.9-hotfix*` build from Nexus and let us know if that resolves the issue. Please revert the configuration change as applied before, that's not needed anymore. Thanks!

**Comment by VBPham** [comment] 2024-01-16 09:16
Hi @jkosternl reverted the suggested workaround of adding the `soapNamespaceSessionKey` attribute to the wrappers and tested with `7.9.0-hotfix4` and it works! Thanks!

**Comment by jkosternl** [comment] 2024-01-17 08:49
> Hi @jkosternl reverted the suggested workaround of adding the `soapNamespaceSessionKey` attribute to the wrappers and tested with `7.9.0-hotfix4` and it works! Thanks!

Great, thanks for letting us know!
