### ISSUE TITLE
When reply is not permitted on a queue, error indication is limited

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#6097] opened 2024-01-11 11:14 UTC
I had a static reply queue which my user was not authorized to send messages to. A few messages were processed by an adapter but there was no indication of errors in the adapter status bar 
![Capture5](https://github.com/frankframework/frankframework/assets/10929856/c8bbfb96-8d86-4ac5-93bc-176864d77b46)

Ladybug shows no error (maybe this is okay since ladybug only shows the pipeline status BUT that could be improved!!)
 
![Capture6](https://github.com/frankframework/frankframework/assets/10929856/d0617ed0-7b10-4729-aae5-eae7698f1e87)

The only place where i could see the error is in this image the Error Messages part but that is also not shining to show itself.
Maybe it could be an improvement to make the color of Error messages text red when it is non-zero 

![Capture7](https://github.com/frankframework/frankframework/assets/10929856/f7fd441f-5621-46ba-bbec-aea2899fa074)

and of course the log file shows the error. However, log file is usually checked when something is wrong in the gui.

**Reporter**
Ali

FF: 7.9-20230811.190015

**Comment by jkosternl** [comment] 2024-01-24 14:05
@alisihab, can you please send me the Ladybug report so I have more clues what detail went wrong and how it was represented in Ladybug? Thanks!

**Comment by alisihab** [comment] 2024-01-25 07:13
Ladybug just shows a successful pipeline. There was not much to see. It is not kept for further references

**Comment by jkosternl** [comment] 2024-01-25 08:32
> Ladybug just shows a successful pipeline. There was not much to see. It is not kept for further references

Yes, that make sense. A Ladybug report also shows the used configuration, which mostly helps us understanding the situation in detail. For me, the last part of your issue we can do (showing 'Error messages' in red color when number of message > 0). But the first part is hard to start working on. It will cost too much time to get your setup reproduced and then hope it will happen.

**Comment by alisihab** [comment] 2024-01-25 09:17
In this issue, the pipeline content is irrelevant. It could just have an echo pipe following success exit. Receiver should have a JmsListener listening to a queue. When sending the jms message on that queue just **set replyTo** header to a queue that the user/application is **not allowed** to send messages to.

**Comment by jkosternl** [comment] 2024-01-31 15:36
Today, we've done some analyses on this issue. 
Reproducing the situation is hard. The easiest way is to add the following method to the class `EsbJmsListener`:
```
@Override
	public String send(MessageProducer messageProducer, javax.jms.Message message, boolean ignoreInvalidDestinationException) throws JMSException {
		logMessageDetails(message, messageProducer);
		throw new JMSException("ShitHappens");
	}```
It will throw a new exception when the EsbJmsListener is trying to return a message. 

A possible solution is to add the following 2 lines to `Receiver#processMessageInAdapter` at line 1293 (after `} catch (Exception e) {`:
```
itx.setRollbackOnly();
messageInError = true;
```
But we are not sure if this has side effects on other code/situations. Secondly, the message was still not found in the ErrorStorage, as we added to the configuration `ConfigurationEsbJmsListenerSender.xml`:
`<errorStorage className="org.frankframework.jdbc.JdbcTransactionalStorage" slotId="${applicationId}/Shit" />` at line 318. We also added `maxDeliveries="2" transacted="required"` to the receiver configuration, but that didn't help. 

It should be discussed at the Monday 13h meeting, with Jaco and Jeroen on how to proceed.

**Comment by nielsm5** [comment] 2024-02-06 09:17
As discussed, when using the RR flow, which is non-transactional, no special action needs to take place, as a lack of a reply will cause the flow to fail. When using an FF flow, which is transactional, there is no response, and thus should it never trigger the flow in question.

**Comment by nielsm5** [comment] 2024-03-28 16:15
Other then logging this, there is not much we can do. The authentication / authorization steps happen at the end of the pipeline (which is why it's not visible in the ladybug), after the message has been processed.
Since it's RR, and there's no transaction, nothing will roll back and the exception will only be logged.

I'm closing this for now. We've made it more clear in the console when exceptions occur. See https://github.com/frankframework/frankframework/issues/6159#issuecomment-1933845556

**Closed by nielsm5** 2024-03-28 16:15 UTC
Labels: Feature
