### ISSUE TITLE
resultQuery input doesnt handle parameters.

### ISSUE THREAD

**Issue by checkiecheck** [frankframework/frankframework#5364] opened 2023-09-11 12:41 UTC
https://github.com/ibissource/iaf/blob/45f585252fe84b0713136c536bea024316fc925a/core/src/main/java/nl/nn/adapterframework/jdbc/JdbcQuerySenderBase.java#L809

using ?{} parameter in resultQuery restults in hard error while executing with error like 
Syntax error in SQL statement "SELECT IDENTIFICATIE FROM IDENTIFICATIE WHERE TYPE = ?{IdentificatieType}[*]" [42000-214]

replacing with hardcoded value makes the query work.

**Comment by checkiecheck** [comment] 2023-09-18 13:25
any parameter.

**Comment by thomaspj10** [comment] 2024-11-08 08:59
You didn't specify a version, so I tested on master. I think that you forget to set the attribute `useNamedParams` to true. I was able to reproduce the error message provided above using an unit test with the same situation, so I will close this issue. The error message is fair, because there is indeed a syntax error. You forgot to enable `useNamedParams`, which caused `?{IdentificatieType}` to not be substituted.

**Comment by nielsm5** [comment] 2024-11-11 12:48
Perhaps you can share the unit-test 😄

**Comment by thomaspj10** [comment] 2024-11-14 14:15
After taking another look it seems that a test (`FixedQuerySenderTest#testNamedParamInQueryFlagFalse)` such as the one, which I wrote already exists.

**Closed by thomaspj10** 2024-11-14 14:15 UTC
